export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_ERROR = 'ON_LOGIN_ERROR';
export const ON_LOGOUT = 'ON_LOGOUT';
export const ON_INVALID_AUTH = 'ON_INVALID_AUTH';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const ON_CADEADOS_LOADING = 'ON_CADEADOS_LOADING';
export const ON_CADEADOS_SUCCESS = 'ON_CADEADOS_SUCCESS';
export const ON_CADEADOS_ERROR = 'ON_CADEADOS_ERROR';
export const ON_CADEADOS_CLEAR = 'ON_CADEADOS_CLEAR';
