export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_ERROR = 'ON_LOGIN_ERROR';
export const ON_LOGOUT = 'ON_LOGOUT';
export const ON_INVALID_AUTH = 'ON_INVALID_AUTH';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const ON_CADEADOS_LOADING = 'ON_CADEADOS_LOADING';
export const ON_CADEADOS_SUCCESS = 'ON_CADEADOS_SUCCESS';
export const ON_CADEADOS_ERROR = 'ON_CADEADOS_ERROR';
export const ON_CADEADOS_CLEAR = 'ON_CADEADOS_CLEAR';
export const ON_CADEADO_SUCCESS = 'ON_CADEADO_SUCCESS';
export const ON_CADEADO_ERROR = 'ON_CADEADO_ERROR';
export const ON_CADEADO_CLEAR = 'ON_CADEADO_CLEAR';
export const ON_REGISTER_CADEADO = 'ON_REGISTER_CADEADO';
export const ON_UPDATE_CADEADO = 'ON_UPDATE_CADEADO';
export const ON_REGISTER_LIBERADOR = 'ON_REGISTER_LIBERADOR';
export const ON_UPDATE_LIBERADOR = 'ON_UPDATE_LIBERADOR';

export const ON_EVENTOS_LOADING = 'ON_EVENTOS_LOADING';
export const ON_EVENTOS_SUCCESS = 'ON_EVENTOS_SUCCESS';
export const ON_EVENTOS_ERROR = 'ON_EVENTOS_ERROR';
export const ON_EVENTOS_CLEAR = 'ON_EVENTOS_CLEAR';
